name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Se ejecuta cuando se crea un tag que comienza con 'v' (ej: v.0)
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub Actions

# Permisos necesarios para crear releases
permissions:
  contents: write  # Necesario para crear releases y subir assets

env:
  PYTHON_VERSION: '3.10'
  APP_NAME: SistemaCriptas

jobs:
  build-windows-installer:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Obtener todo el historial para tags

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip

        # Instalar cada dependencia explicitamente
        pip install SQLAlchemy==2.0.43
        pip install reportlab==4.4.3
        pip install Pillow==11.3.0
        pip install schedule==1.2.2
        pip install requests>=2.31.0
        pip install python-dateutil==2.9.0.post0
        pip install shortuuid==1.0.13
        pip install packaging==25.0
        pip install openpyxl==3.1.5
        pip install pandas==2.3.2
        pip install pywin32-ctypes==0.2.3
        pip install altgraph==0.17.4
        pip install charset-normalizer==3.4.3
        pip install et-xmlfile==2.0.0
        pip install greenlet==3.2.4
        pip install numpy==2.3.2
        pip install pefile==2023.2.7
        pip install pyinstaller==6.15.0
        pip install pyinstaller-hooks-contrib==2025.8
        pip install pytz==2025.2
        pip install six==1.17.0
        pip install typing_extensions==4.15.0
        pip install tzdata==2025.2
        pip install tkcalendar==1.6.1

    - name: Verificar instalaciones criticas
      run: |
        python -c "import schedule; print('[OK] schedule instalado:', schedule.__version__)"
        python -c "import sqlalchemy; print('[OK] sqlalchemy instalado:', sqlalchemy.__version__)"
        python -c "import reportlab; print('[OK] reportlab instalado:', reportlab.__version__)"
        python -c "import requests; print('[OK] requests instalado:', requests.__version__)"
        python -c "import pandas; print('[OK] pandas instalado:', pandas.__version__)"
        python -c "import openpyxl; print('[OK] openpyxl instalado:', openpyxl.__version__)"

    - name: Obtener versión del tag
      id: get_version
      shell: bash
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION="dev-$(git rev-parse --short HEAD)"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Versión: $VERSION"

    - name: Instalar Inno Setup con Chocolatey
      shell: powershell
      run: |
        Write-Host "Instalando Inno Setup via Chocolatey..."
        choco install innosetup -y

        # Refrescar variables de entorno
        $env:ChocolateyInstall = Convert-Path "$((Get-Command choco).Path)\..\.."
        Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        refreshenv

        Write-Host "Verificando instalacion..."
        $InnoPath = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
        if (Test-Path $InnoPath) {
          Write-Host "[OK] Inno Setup instalado correctamente"
          Write-Host "Ruta: $InnoPath"

          # Agregar al PATH para este step
          $InnoDir = Split-Path -Parent $InnoPath
          echo "$InnoDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        } else {
          Write-Host "[ERROR] Inno Setup no se instalo correctamente"
          Write-Host "Buscando en otras ubicaciones..."
          Get-ChildItem -Path "C:\Program Files*" -Filter "ISCC.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object FullName
          exit 1
        }

    - name: Crear directorios y archivos necesarios
      shell: powershell
      run: |
        # Crear directorios solo si no existen
        $dirs = @('assets', 'database', 'ui', 'reports', 'backup')
        foreach ($dir in $dirs) {
          if (-not (Test-Path $dir)) {
            New-Item -ItemType Directory -Path $dir -Force
            Write-Host "[OK] Creado directorio: $dir"
          } else {
            Write-Host "[INFO] Directorio ya existe: $dir"
          }

          # Crear __init__.py en módulos Python si no existe
          if ($dir -ne 'assets') {
            $initFile = Join-Path $dir "__init__.py"
            if (-not (Test-Path $initFile)) {
              New-Item -ItemType File -Path $initFile -Force | Out-Null
              Write-Host "[OK] Creado $initFile"
            }
          }
        }

        # Crear archivo de icono placeholder si no existe
        $iconPath = "assets\icon.ico"
        if (-not (Test-Path $iconPath)) {
          Write-Host "[INFO] Creando icono placeholder..."
          # El script de Python creará el icono si no existe
        }

    - name: Construir ejecutable e instalador
      run: |
        python build_installer.py --version ${{ steps.get_version.outputs.VERSION }}

    - name: Verificar archivos generados
      shell: bash
      run: |
        ls -lh dist/
        ls -lh dist/installer/

        # Verificar que el instalador fue creado
        INSTALLER="dist/installer/${APP_NAME}_Setup_v${{ steps.get_version.outputs.VERSION }}.exe"
        if [ -f "$INSTALLER" ]; then
          echo "[OK] Instalador creado: $INSTALLER"
          SIZE=$(du -h "$INSTALLER" | cut -f1)
          echo "  Tamano: $SIZE"
        else
          echo "[ERROR] No se encontro el instalador"
          exit 1
        fi

    - name: Subir instalador como artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: dist/installer/${{ env.APP_NAME }}_Setup_v${{ steps.get_version.outputs.VERSION }}.exe
        retention-days: 30

    - name: Subir notas de versión como artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-notes
        path: dist/installer/Release_Notes_v${{ steps.get_version.outputs.VERSION }}.md
        retention-days: 30

    - name: Crear Release en GitHub
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/installer/${{ env.APP_NAME }}_Setup_v${{ steps.get_version.outputs.VERSION }}.exe
          dist/installer/Release_Notes_v${{ steps.get_version.outputs.VERSION }}.md
        body_path: dist/installer/Release_Notes_v${{ steps.get_version.outputs.VERSION }}.md
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notificar resultado
      if: always()
      shell: bash
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "[SUCCESS] Build completado exitosamente"
          echo "Version: ${{ steps.get_version.outputs.VERSION }}"
        else
          echo "[FAILED] Build fallo"
        fi
